### ISSUE TITLE
tech_stack = tech_stack.split(';')

### ISSUE THREAD

**Issue by ArtemKonshyn** [M-Garkaviuk/alevel_hw#5]
https://github.com/M-Garkaviuk/alevel_hw/blob/8bcfde8007355c8184800fc95e66e0d3ea0824f2/Lesson_17_hw/Lesson_18_hw/Lesson_18_hw.py#L37

так буде отаке
['Python|CSS']
тобто 1 строка
а нам потрібен список із окемих строк-скілів

**Comment by M-Garkaviuk** [comment]
Виправлено tech_stack = tech_stack.split('|')

:)
